[
  {
    id: 1,
    category: "Technical",
    Event: "LAN Gaming ( Mini militia (Mobile Game) PUB-G New State (Mobile Game)  Valorant (PC Game) )",
    pricing: "100/ - per person Mini militia, 300/- per Team PUB-G New State 100/-person, 400 Rs. Per Team (Max Team Size 5 - Valorant) (PC Game) &amp;\n(100/-person for individual)",
    img: "https://i.ibb.co/2Zt7wjC/9.png",
    venue: "HP-Lab 1-2 & 108 TB-1,VLSI LAB",
  },
  {
    id: 1,
    category: "Technical (LAN Gaming)",
    Event: "Mini militia (Mobile Game)",
    pricing: "Rs 100/ - per person",
    img: "https://i.ibb.co/2Zt7wjC/9.png",
    venue: "HP-Lab 1-2 & 108 TB-1,VLSI LAB",
  },
  {
    id: 2,
    Event: "PUB-G New State (Mobile Game)",
    pricing: "Rs 100/-person and 300/- per Team",
    img: "https://i.ibb.co/2Zt7wjC/9.png",
    venue: "HP-Lab 1-2 & 108 TB-1,VLSI LAB"
  },
  {
    id: 3,
    Event: "Valorant (PC Game)",
    pricing: "Rs 100/-person for individual and 400 Rs. Per Team  (Max Team Size 5)",
    img: "https://i.ibb.co/2Zt7wjC/9.png",
    venue: "HP-Lab 1-2 & 108 TB-1,VLSI LAB"
  },
  {
    id: 4,
    category: "Technical",
    Event: "Paper Presentation",
    pricing: "Rs 100/- Per Person",
    img: "https://i.ibb.co/8KXKmQ7/10.png",
    venue: "AU Seminar Hall [11:00-03:00]",
  },
  {
    id: 5,
    Event: "Code Hunt",
    pricing: "Rs 100/- Per Person",
    img: "https://i.ibb.co/BycMXPP/11.png",
    venue: "Dell Lab[11:00-03:00]",
  },
  {
    id: 6,
    Event: "Assemble and Disassemble",
    pricing: "Rs 100/- Per Person",
    img: "https://i.ibb.co/6g8LVT8/12.png",
    venue: "C-4 & C-7 [11:00-04:00]",
  },
  {
    id: 7,
    Event: "Circuit Designing",
    pricing: "Rs 300/- per Team\n(Max size 3)",
    img: "https://i.ibb.co/hBTkzGW/13.png",
    venue: "EC Seminar Hall [11:00-04:00]",
  },
  {
    id: 8,
    Event: "Lensense & Photography Workshop cum Contest",
    pricing: "Rs 100/- Per Person",
    img: "https://i.ibb.co/SxL1YBD/14.png",
    venue: "IDEA Lab [11:00-02:00]",
  },
  {
    id: 9,
    Event: "Project/Model and Mega Structure Competition",
    pricing: "Rs 100/- Per Person",
    img: "sad",
    venue: "LT-2 (EX),D1,SAC [11:00-04:00]",
  },
  {
    id: 10,
    Event: "Art-Junkies\n(Best out of waste)",
    pricing: "Rs.100/- Per Person",
    img: "https://i.ibb.co/KFqnSGL/16.png",
    venue: "30 (TB-1) [11:00-04:00],day 2",
  },
  {
    id: 11,
    Event: "Robodino Competition (Robotics, Robo Race, Line Follower, Gripper)",
    pricing: "Rs 300/- Team (Max Team size 4)",
    img: "https://i.ibb.co/X4WKTyj/17.png",
    venue: "open Area In front of Central Library & R.no 001,002 TB -1 [Dark Room]",
  },
  {
    id: 1,
    category: "Mega Event/Games",
    Event: "Water Rocket Propulsion",
    pricing: "Rs 300/- Per Team\n(Team Size max 3)",
    img: "https://i.ibb.co/Pz2RDXt/3.png",
    venue: "OCT Ground [10:00-12:00],Day 3",
  },
  {
    id: 2,
    category: "Mega Event/Games (Talent Star Light)",
    Event: "Singing",
    pricing: "Rs 200/- Per Person\n",
    img: "https://i.ibb.co/Tgqc4Xm/4.png",
    venue: "Day 1-AUDI {TSL}[11:00-03:00], Day 2-AUDI {TSL}[11:00-03:00]",
  },
  {
    id: 3,
    Event: "Dancing",
    pricing: "Rs 200/- Per Person, 500/-Rs per Team Max 5 and Rs 100 per person for above 5 members",
    img: "https://i.ibb.co/Tgqc4Xm/4.png",
    venue: "Day 1-AUDI {TSL}[11:00-03:00], Day 2-AUDI {TSL}[11:00-03:00]",
  },
  {
    id: 4,
    Event: "Instrumental",
    pricing: "Rs 200/- Per Person and Rs 500/- per Team",
    img: "https://i.ibb.co/Tgqc4Xm/4.png",
    venue: "Day 1-AUDI {TSL}[11:00-03:00], Day 2-AUDI {TSL}[11:00-03:00]",
  },
  {
    id: 5,
    Event: "Poetry",
    pricing: "Rs 200/- Per Person",
    img: "https://i.ibb.co/Tgqc4Xm/4.png",
    venue: "Day 1-AUDI {TSL}[11:00-03:00], Day 2-AUDI {TSL}[11:00-03:00]",
  },
  {
    id: 6,
    Event: "Mime",
    pricing: "Rs 200/- Per Person",
    img: "https://i.ibb.co/Tgqc4Xm/4.png",
    venue: "Day 1-AUDI {TSL}[11:00-03:00], Day 2-AUDI {TSL}[11:00-03:00]",
  },
  {
    id: 7,
    Event: "Band Show",
    pricing: "Rs 200/- Per Person and Rs 500/- per Team(Bandshow)- (Max 5 and Rs 100 per person for above 5 members)",
    img: "https://i.ibb.co/KjSdzJ8/23.png",
    venue: "AUDI{TSL}[11:00-03:00],Day 2",
  },
  {
    id: 8,
    category: "(Mega Event/Games)",
    Event: "Treasure Hunt",
    pricing: "Rs 100/- per person",
    img: "https://i.ibb.co/mBrWgQ6/5.png",
    venue: "abc",
  },
  {
    id: 10,
    Event: "Fiesta Evening",
    pricing: "Rs 300/- per person",
    img: "sad",
    venue: "OCT GROUND [06:00-10:00]",
  },
  {
    id: 11,
    Event: "Roadies Battle Yard &amp; Stunt Show",
    pricing: "Rs.100/- per person",
    img: "https://i.ibb.co/YW5mj6Q/6.png",
    venue: "Day1-LT-1 & OCT Ground/Road [12:00-04:00] ,Day2-OCT Road[12:00-04:00]",
  },
  {
    id: 12,
    Event: "Traditional Fashion Show",
    pricing: "Rs. 300/- per person",
    img: "https://i.ibb.co/Xjyp936/7.png",
    venue: "Day1-AUDI [03:00-06:00] ,Day2-OCT Ground [04:00-06:00] ",
    
  },
  {
    id: 13,
    Event: "100 Rs Venture",
    pricing: "Rs 500/- per Team (Team Size Max 5)",
    img: "https://i.ibb.co/8D0byJ9/8.png",
    venue: "IDEA Lab and Nearby area[11:00-05:00]",
  },
  {
    id: 1,
    category: "Sports Event",
    Event: "Volleyball",
    pricing: "Rs 600/- per team(Max 6 members)",
    img: "https://i.ibb.co/zfTf6dL/24.png",
    venue: "1st ,3rd and 5th April Volleyball Court",
  },
  {
    id: 2,
    Event: "Badminton",
    pricing: "Rs 100/- single and Rs 200/- for Doubles",
    img: "https://i.ibb.co/0Fbb7YK/27.png",
    venue: "1st ,3rd and 5th April Badminton Court Near Boys Hostel",
  },
  {
    id: 3,
    Event: "Cricket",
    pricing: "Rs 1100/- per team",
    img: "https://i.ibb.co/nn82mgV/30.png",
    venue: "27-29 &31 March, 01,03,05 April [7:00-11:00 AM & 3:00-7:00 PM]",
  },
  {
    id: 4,
    Event: "Chess",
    pricing: "Rs 100/- per person",
    img: "sad",
    venue: "5th April [108]TB-1",
  },
  {
    id: 5,
    Event: "Basket ball",
    pricing: "Rs 500/- per team",
    img: "https://i.ibb.co/bLXjDvM/29.png",
    venue: "3rd & 5th Basket ball ground",
  },
  {
    id: 6,
    Event: "Futsal",
    pricing: "Rs 700/- per team",
    img: "https://i.ibb.co/wW8v9yM/25.png",
    venue: "3rd & 5th School Ground",
  },
  {
    id: 7,
    Event: "Kabbadi",
    pricing: "Rs 700/- per team",
    img: "https://i.ibb.co/ZKGzZFN/28.png",
    venue: "3rd & 5th Oct Ground",
  },
  {
    id: 1,
    category: "Cultural",
    Event: "Face Painting",
    pricing: "Rs 100/- per person",
    img: "https://i.ibb.co/CMSkdZb/18.png",
    venue: "BS Foyer [11:00-03:00]",
  },
  {
    id: 4,
    Event: "Admad Show",
    pricing: "Rs 100/- per person",
    img: "https://i.ibb.co/r2W9Lrm/19.png",
    venue: "CE Seminar Hall[11:00-03:00]",
  },
  {
    id: 5,
    Event: "Extempore",
    pricing: "Rs 100 Per Person",
    img: "https://i.ibb.co/PWwLGQL/20.png",
    venue: "CE Seminar Hall[11:00-03:00],Day-2",
  },
  {
    id: 6,
    Event: "Mock Parliament",
    pricing: "Rs.100 Per Person",
    img: "https://i.ibb.co/tcpGxvr/21.png",
    venue: "OCM Seminar Hall [11:00-04:00],Day-2",
  },
  {
    id: 7,
    Event: "Mega Workshop/Lecture Series",
    pricing: "Rs 200/- per person",
    img:"https://i.ibb.co/qRx2Ty9/22.png",
    venue:"AUDI[10:00-12:00],Day 3"
  }
]
